package com.quickshare.backend.dto.room;

import com.quickshare.backend.model.enums.RoomVisibility;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CreateRoomRequest {

    @Schema(description = "Custom name for the room. Optional – autogenerated if not provided")
    private String customRoomName;

    @Schema(description = "Room visibility setting (e.g., PUBLIC or PRIVATE)")
    private RoomVisibility visibility;

    @Schema(description = "Room expiration time in hours (e.g., 24 for 1 day)")
    private Integer expirationHours;

    @Schema(description = "If true, only the room creator can upload files")
    private Boolean creatorOnlyUpload;

    @Schema(description = "Maximum total storage allowed for this room in bytes")
    private Long maxStorageBytes;

    @Schema(description = "Maximum number of participants allowed in the room")
    private Integer maxParticipants;

    @NotBlank(message = "User ID is required")
    @Schema(description = "Unique user ID of the room creator")
    private String userId;
}