package com.quickshare.backend.dto.room;

import com.quickshare.backend.model.enums.RoomVisibility;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CreateRoomRequest {

    @Schema(description = "Custom name for the room. Optional – autogenerated if not provided")
    @Size(max = 100, message = "customRoomName must be at most 100 characters")
    private String customRoomName;

    @Schema(description = "Room visibility setting (e.g., PUBLIC or PRIVATE)")
    private RoomVisibility visibility;

    @Schema(description = "Room expiration time in hours (e.g., 24 for 1 day)")
    @Min(value = 1, message = "expirationHours must be at least 1")
    @Max(value = 720, message = "expirationHours must be at most 720")
    private Integer expirationHours;

    @Schema(description = "If true, only the room creator can upload files")
    private Boolean creatorOnlyUpload;

    @Schema(description = "Maximum total storage allowed for this room in bytes")
    private Long maxStorageBytes;

    @Schema(description = "Maximum number of participants allowed in the room")
    @Min(value = 2, message = "maxParticipants must be at least 2")
    @Max(value = 500, message = "maxParticipants must be at most 500")
    private Integer maxParticipants;

    @NotBlank(message = "User ID is required")
    @Schema(description = "Unique user ID of the room creator")
    private String userId;

    @Schema(description = "Mark room as Featured", defaultValue = "false")
    private Boolean isFeatured;
}
